In [1]:
#lets say we dont have numpy 

In [2]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

a+b 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
#lets say i want to add first element of list with another list's first element
k = []
for i,j in zip(a,b):
    k.append(i+j)
k

[7, 9, 11, 13, 15]

In [4]:
#above methods are not useful  for multi dimensional list, slow .


In [5]:
import numpy as np 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype  # this shows that every elements inside of a numpy array type is set as int32

dtype('int32')

In [8]:
f = np.array([1.2,8.9,3,5])
f.dtype

dtype('float64')

In [9]:
#access value from numpy array 
a[0]

1

In [11]:
#assign value into it 
a[0] = 11.6  #here it will take value as 11 .. as numpy elemetns have to be same type
a

array([11,  2,  3,  4,  5])

In [12]:
a.ndim  #value of no of dimension of an array 

1

In [13]:
a.shape #shape always return tupple. it will show the total elements along the dimension 
#consider we got result of the shape like (3,5,6,) then its show that we have totol three dimension first dimension has 3 elements second has 5 and third has 6 elements

(5,)

In [14]:
a.size # its give total no of the elements in the array 

5

In [15]:
a+f 

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [17]:
#here shape of a and f is not same so i cant add them 
b= np.array([6,7,8,9,10])

In [18]:
a+b   #here we can see it will add elements to elements .. it doesnt concat two array 

array([17,  9, 11, 13, 15])

In [19]:
c = np.array([1.2,3,4,5.5,6.8])
a+c

array([12.2,  5. ,  7. ,  9.5, 11.8])

In [20]:
a*c

array([13.2,  6. , 12. , 22. , 34. ])

In [21]:
a/c

array([9.16666667, 0.66666667, 0.75      , 0.72727273, 0.73529412])

In [22]:
a/b

array([1.83333333, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [24]:
a**c  #all operation will perform elements vice

array([1.77693369e+01, 8.00000000e+00, 8.10000000e+01, 2.04800000e+03,
       5.66234112e+04])

In [25]:
a*10

array([110,  20,  30,  40,  50])

In [26]:
a

array([11,  2,  3,  4,  5])

In [27]:
np.sin(a)

array([-0.99999021,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [31]:
a.fill(-3.8)
a

array([-3, -3, -3, -3, -3])

In [32]:
a.fill(5.8)   #will always return int type 
a

array([5, 5, 5, 5, 5])

In [33]:
a.dtype

dtype('int32')

2-D

In [37]:
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [38]:
a.shape

(2, 4)

In [39]:
a.size

8

In [40]:
a.ndim

2

In [41]:
a[0]

array([0, 1, 2, 3])

In [42]:
a[1]

array([10, 11, 12, 13])

In [43]:
a[1,3]

13

In [44]:
a[1,3] = 9
a

array([[ 0,  1,  2,  3],
       [10, 11, 12,  9]])

slicing 

In [45]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [46]:
a[1:3]

array([2, 3])

In [47]:
a[1:-2]

array([2, 3])

In [48]:
a[-4:3]

array([2, 3])

In [49]:
a[:3] #first three ele

array([1, 2, 3])

In [50]:
a[-2:] #last two ele

array([4, 5])

In [51]:
a[::2] #step of 2 

array([1, 3, 5])

In [52]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
a.ndim

2

In [54]:
a.shape

(4, 5)

In [55]:
a[0,2:4]  #first row 2:4  //row selection 

array([3, 4])

In [56]:
a[2: , 3: ]

array([[14, 15],
       [19, 20]])

In [57]:
a[ : , 2] #coloum selection  #not that silicing result may have diff dimension than a 

array([ 3,  8, 13, 18])

In [59]:
a[: , 2:4] 

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [63]:
a= np.arange(2,27).reshape(5,5)
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [64]:
a[-1, ]

array([22, 23, 24, 25, 26])

In [65]:
a[ : , 1::2 ]

array([[ 3,  5],
       [ 8, 10],
       [13, 15],
       [18, 20],
       [23, 25]])

In [70]:
a[1::2, 0:3:2]

array([[ 7,  9],
       [17, 19]])

In [71]:
b = a[4, : ]

In [74]:
b.shape
b.ndim

1

In [75]:
b= a[4]
b.shape
b.ndim

1

In [76]:
b

array([22, 23, 24, 25, 26])

In [77]:
b[0] = -1 
b

array([-1, 23, 24, 25, 26])

In [78]:
a  #here we can see a array value also changed even if we have changed value of b

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [-1, 23, 24, 25, 26]])

In [79]:
#reason behind if we have written b = a[4]  .. so here it is consider as a shallow copy in python 
a = np.arange(25).reshape(5,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
b= a[::]  #it is not the solution in array case 
b= a[4]
b[0]=-1
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [-1, 21, 22, 23, 24]])

In [81]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
b = a[4].copy()  #this is proper solution ..always use .copy method for deep copy in python
# clear the cocepts of memory and OOP to understand shallow and deep copy 

In [83]:
b

array([20, 21, 22, 23, 24])

In [84]:
b[0]=-1
b

array([-1, 21, 22, 23, 24])

In [85]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
a= np.arange(0,5).reshape(5)
a


array([0, 1, 2, 3, 4])

In [94]:
a[-2:]

array([3, 4])

In [95]:
a[-2:]  = [32,44]
a

array([ 0,  1,  2, 32, 44])

In [96]:
a[-2:] = 100

In [97]:
a

array([  0,   1,   2, 100, 100])

Fancy Indexing 

In [98]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [99]:
idx = [1,2,-3]
y = a[idx]

In [100]:
y

array([10, 20, 50])

In [101]:
y[0] = -1  #no effect on a if we pass array for indexing it will create new object. 
a


array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [102]:
y 

array([-1, 20, 50])

In [103]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [104]:
a[idx] = 100
a

array([  0, 100, 100,  30,  40, 100,  60,  70])

In [106]:
mask = np.array([0,1,1,1,0,0,1,1],dtype=bool)
y = a[mask]
y

array([100, 100,  30,  60,  70])

In [107]:
mask

array([False,  True,  True,  True, False, False,  True,  True])

In [108]:
a = np.array([-1,-2,-9,34,543,-92])
a<0  #mask value according to condition 

array([ True,  True,  True, False, False,  True])

In [109]:
a[a<0]

array([ -1,  -2,  -9, -92])

In [110]:
a[a>0]

array([ 34, 543])

In [111]:
a[a<0] = 0
a

array([  0,   0,   0,  34, 543,   0])

2-D

In [112]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
a[[0,1,2,3,4],[1,2,3,4,0]]  #first list show row select and sencod one shows coloum select

array([ 1,  7, 13, 19, 20])

In [114]:
a[2: , [0,1,4]]

array([[10, 11, 14],
       [15, 16, 19],
       [20, 21, 24]])

In [115]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [116]:
a[[0,2,3,3],[2,3,4,1]]

array([ 2, 13, 19, 16])

In [117]:
np.nan

nan

In [118]:
np.nan + 23

nan

Array broadcasting

In [119]:
a = np.ones((3,5))

In [120]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
b = np.ones((5,))
b

array([1., 1., 1., 1., 1.])

In [130]:
b= b.reshape(1 , 5) #to make inner dimension equal 


In [131]:
b.shape

(1, 5)

In [132]:
b

array([[1., 1., 1., 1., 1.]])

In [133]:
a+b  #array is repeated 

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [134]:
a = np.array([[0],[10],[20],[30]])
a

array([[ 0],
       [10],
       [20],
       [30]])

In [135]:
a.shape 

(4, 1)

In [137]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [138]:
b.shape 

(3,)

In [141]:
b = b.reshape(1, 3) 


In [142]:
b.shape

(1, 3)

In [143]:
a+b 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

Array Calculation 

In [144]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
a.sum()

21

In [147]:
a.sum(axis = 0)

array([5, 7, 9])

In [148]:
a.sum(axis=1)

array([ 6, 15])

In [149]:
a = np.array([[2,3],[0,1]])
a.min()

0

In [150]:
a.max()

3

In [151]:
a.max(axis=0)

array([2, 3])

In [152]:
a.max(axis=1)

array([3, 1])

In [153]:
a.argmax()

1

In [154]:
a.argmin() #it will flatten the multi dime array to single dime

2

In [156]:
np.unravel_index(a.argmax(),a.shape) #this will give relative position of first matching element in array 

(0, 1)

In [157]:
np.unravel_index(a.argmin(),a.shape) 

(1, 0)

Where  //if there are multiple match we can use this method to access the index of all matching elements

In [159]:
a = np.arange(-2,2)
a

array([-2, -1,  0,  1])

In [160]:
a = a **2

In [161]:
a

array([4, 1, 0, 1], dtype=int32)

In [163]:
np.where(a==0) #return the all matching index

(array([2], dtype=int64),)

In [164]:
np.where(a==1)

(array([1, 3], dtype=int64),)

In [178]:
a = np.array([[1,2],[2,0]])
a

array([[1, 2],
       [2, 0]])

In [179]:
np.where(a== a.max())

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [181]:
a==a.max()

array([[False,  True],
       [ True, False]])

In [188]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [189]:
a.T  #swap order of axis

array([[0, 3],
       [1, 4],
       [2, 5]])

In [190]:
#for reshape 
#a =a.reshape()
#a.shape= ()


Flatten

In [191]:
a= np.array([[0,1],[2,3]])
b= a.flatten()  #return copy of the a and flatten it .. deep copy 

In [192]:
b

array([0, 1, 2, 3])